name: Remove Developer from Awesome List
description: Remove a developer from the directory
title: "[REMOVE] @{github_username}"
labels: ["remove-developer"]
body:
  - type: input
    id: github_username
    attributes:
      label: GitHub Username
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: Reason for removal
    validations:
      required: true
  - type: checkboxes
    id: self_removal
    attributes:
      label: Self-removal
      options:
        - label: "I am removing my own profile"
