import json
import os
from datetime import datetime, timezone

def generate_readme():
    enriched_path = 'data/users-enriched.json'
    cname_path = 'CNAME'
    
    if not os.path.exists(cname_path):
        _cname_content = "#"
    else:
        with open(cname_path, 'r') as f:
            _cname_content = f.read().strip()
            
    if not os.path.exists(enriched_path):
        print(f"Error: {enriched_path} not found.")
        # Create a basic README if no data
        with open('README.md', 'w') as f:
            f.write("# Awesome Bangladeshi Devs\n\nData-driven directory of Bangladeshi GitHub developers. Rebuild in progress.")
        return
        
    with open(enriched_path, 'r') as f:
        users = json.load(f)
        
    last_updated = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    
    # Top 500 by overall score
    top_by_score = sorted(users, key=lambda x: x.get('activity_score', 0), reverse=True)[:500]
    
    # Calculate top community language
    languages = [u.get('top_language') for u in users if u.get('top_language')]
    top_lang = "N/A"
    if languages:
        top_lang = max(set(languages), key=languages.count)

    readme_content = f"""# Awesome Bangladeshi Devs
[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)
[![Pipeline Status](https://github.com/sharf-shawon/Awesome-Bangladeshi-Devs/actions/workflows/pipeline.yml/badge.svg)](https://github.com/sharf-shawon/Awesome-Bangladeshi-Devs/actions/workflows/pipeline.yml)
[![GitHub last commit](https://img.shields.io/github/last-commit/sharf-shawon/Awesome-Bangladeshi-Devs)](#)

## Data-driven directory of **{len(users):,}** Bangladeshi GitHub developers.

## For better experience and finding developers with specific skills around Bangladesh, please visit [{_cname_content}](https://{_cname_content}/).

## Contents

- [Top 500 Developers (by Activity Score)](#top-500-developers-by-activity-score)
- [Stats](#stats)
- [How to Add Yourself](#how-to-add-yourself)

---

## Top 500 Developers (by Activity Score)

| Rank | Avatar | User | Score | Followers | Stars | Top Language |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
"""

    for i, user in enumerate(top_by_score):
        avatar = f"<img src='{user.get('avatar_url', '')}' width='40' height='40'>"
        username = f"[@{user['github_username']}](https://github.com/{user['github_username']})"
        score = user.get('activity_score', 0)
        followers = user.get('followers', 0)
        stars = user.get('total_stars', 0)
        lang = user.get('top_language', 'N/A')
        
        readme_content += f"| {i+1} | {avatar} | {username} | {score} | {followers} | {stars} | {lang} |\n"

    readme_content += f"""
---

## Stats

- Total Developers: {len(users):,}
- Total Stars: {sum(u.get('total_stars', 0) for u in users):,}
- Top Community Language: {top_lang}

## How to Add Yourself

Please open an [Add Developer Issue](https://github.com/sharf-shawon/Awesome-Bangladeshi-Devs/issues/new?template=add_developer.yml) and fill in your GitHub username and location. The pipeline will automatically validate and add you to the list!

---
*Auto-generated by `generate_readme.py` on {last_updated}*
"""

    with open('README.md', 'w') as f:
        f.write(readme_content)
        
    print("Successfully generated README.md")

if __name__ == "__main__":
    generate_readme()
